title: Love ◦ Sex ◦ Fur
email: submit@adjectivespecies.com
description: Love and Sex in the Furry Subculture
baseurl: ""
url: "http://lovesexfur.com"
twitter_username: adjspecies
github_username:  adjspecies

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
